#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_NON_ROOT_USER WITH ENCRYPTED PASSWORD '$POSTGRES_NON_ROOT_PASSWORD';
    CREATE DATABASE $POSTGRES_DATABASE ENCODING 'UTF8'  OWNER $POSTGRES_NON_ROOT_USER;
EOSQL